#:schema node_modules/wrangler/config-schema.json
name = "jaeger-ai"
main = "_worker.js"
compatibility_date = "2025-10-14"

# Assets configuration for Cloudflare Pages
[site]
bucket = "."

# Production environment
[env.production]
name = "jaeger-ai-production"

# Environment variables (set via wrangler CLI or dashboard)
# wrangler secret put JAEGER_API_URL
# wrangler secret put API_TOKEN
