version: '3.8'

services:
  jaeger-ai:
    build: .
    container_name: jaeger-ai-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - jaeger-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  jaeger-network:
    driver: bridge